# Generated by Django 5.2.5 on 2025-11-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Manaus', max_length=100)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('ponto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto.ponto')),
            ],
        ),
    ]
